# This workflow will do a clean install of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  unit:
    name: Unit Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
#        cache: yarn
        node-version-file: .nvmrc
#        corepack: true
    - name: Install dependencies
      run: corepack enable && yarn install
    - name: Type check
      run: yarn type-check
#    - name: Run unit tests
#      run: yarn test:unit
  lint:
    name: Linters
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: true
    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
#        cache: yarn
        node-version-file: .nvmrc
#        corepack: true
    - name: Install dependencies
      run: corepack enable && yarn install
    - name: Run ESLint
      run: yarn lint
    - name: Run Stylelint
      run: yarn run stylelint
